# Generated by Django 5.0.3 on 2024-04-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datos_Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(max_length=50)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(max_length=50)),
                ('documento', models.CharField(max_length=10)),
                ('numero_documento', models.IntegerField()),
                ('correo', models.TextField()),
                ('celular', models.IntegerField()),
                ('ciudad', models.TextField(max_length=60)),
                ('direccion', models.TextField()),
                ('ingresos', models.IntegerField()),
                ('actividad', models.TextField()),
                ('franquicia', models.CharField(max_length=50)),
            ],
        ),
    ]
