# Generated by Django 5.0.3 on 2024-04-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormModule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_usuario',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='datos_usuario',
            name='documento',
            field=models.IntegerField(choices=[(0, 'Cédula de Ciudadanía'), (1, 'Pasaporte'), (2, 'Cédula de Extranjería')]),
        ),
        migrations.AlterField(
            model_name='datos_usuario',
            name='franquicia',
            field=models.IntegerField(choices=[(0, 'Visa'), (1, 'MasterCard'), (2, 'AmericanExpress')]),
        ),
    ]
