# Generated by Django 5.0.3 on 2024-04-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormModule', '0002_alter_datos_usuario_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_usuario',
            name='ciudad',
            field=models.CharField(max_length=60),
        ),
    ]
