# Generated by Django 5.0.3 on 2024-04-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormModule', '0003_alter_datos_usuario_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_usuario',
            name='actividad',
            field=models.CharField(max_length=50),
        ),
    ]
