# Generated by Django 5.0.3 on 2024-04-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormModule', '0004_alter_datos_usuario_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_usuario',
            name='celular',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='datos_usuario',
            name='documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('Pasaporte', 'Pasaporte'), ('CedulaExtranjeria', 'Cédula de Extranjería')], max_length=50),
        ),
        migrations.AlterField(
            model_name='datos_usuario',
            name='franquicia',
            field=models.CharField(choices=[('Visa', 'Visa'), ('MasterCard', 'MasterCard'), ('AmericanExpress', 'American Express')], max_length=50),
        ),
        migrations.AlterField(
            model_name='datos_usuario',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datos_usuario',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
